// <auto-generated />
using AircraftStateCore.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AircraftStateCore.Database.Migrations
{
    [DbContext(typeof(AircraftStateContext))]
    partial class AircraftStateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("AircraftStateCore.DAL.DatabaseContext.ApplicationSettingsDatum", b =>
                {
                    b.Property<string>("DataKey")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("DataValue")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("DataKey");

                    b.ToTable("applicationSettings", (string)null);
                });

            modelBuilder.Entity("AircraftStateCore.DAL.DatabaseContext.PlaneDatum", b =>
                {
                    b.Property<string>("Plane")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("plane");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.HasKey("Plane");

                    b.ToTable("planeData", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AircraftStateCore.DAL.DatabaseContext.ProfileDatum", b =>
                {
                    b.Property<string>("ProfileName")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("profileName");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.HasKey("ProfileName");

                    b.ToTable("profileData", (string)null);
                });

            modelBuilder.Entity("AircraftStateCore.DAL.DatabaseContext.SettingsDatum", b =>
                {
                    b.Property<string>("DataKey")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("DataValue")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("DataKey");

                    b.ToTable("settings", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
